abstract: Double Click Starts Edit
author: "Ingy d\xC3\xB6t Net <ingy@cpan.org>"
distribution_type: module
generated_by: Module::Install version 0.61
license: perl
name: Kwiki-DoubleClickToEdit
no_index: 
  directory: 
    - inc
    - t
requires: 
  Kwiki: 0.38
  perl: 5.6.1
version: 0.10
